'use strict';
const slides = [...document.querySelectorAll('.slide')];
const notes = [
 {title:'Visión · 1:30', script:'Una planta no necesita otra alerta; necesita saber qué hacer mientras todavía está produciendo. Made OS conecta las señales físicas con el contexto operativo y convierte esa información en una acción. Ahora incorporamos System One para evaluar en milisegundos y hacer más rápida esa decisión. Nuestra visión es que Made OS sea el cerebro operativo de la planta: leer, entender y prescribir antes de perder producción.', focus:'Abre con el resultado industrial. Explica que “zero-loss” es la visión, no una garantía de cero fallas. El 55% corresponde a Made OS antes de System One.', bridge:'Para entender por qué importa, veamos dónde se pierde hoy la oportunidad de actuar.', source:'Brief de Made para CSC 2026; documentación “Next of Made”. La condición Top 30 es información proporcionada por Made.'},
 {title:'Problema y mercado · 2:30', script:'La falla visible llega al final. Antes, la máquina ya mostró señales: una deriva de vibración, una variación de corriente, un patrón térmico distinto. Pero esos datos están separados del historial de mantenimiento y del calendario de producción. El equipo tarda en unirlos y una falla local se convierte en producción perdida, reparación de emergencia y retrasos de entrega. Nuestro mercado inicial son operaciones donde ese costo es medible: manufactura de materiales, líneas críticas y distribución pesada.', focus:'Dedica un minuto a cómo se calcula el costo: margen de producción perdido + costos incrementales de reparación, reinicio y penalizaciones, evitando doble conteo. No presentes un TAM inventado. Cliente: responsable de planta/mantenimiento; entrada: activo crítico con señales disponibles.', bridge:'Made conecta ese contexto sin sustituir la infraestructura que la planta ya tiene.', source:'Brief del usuario; documentación interna de Made. El esquema financiero es explicativo, sin cifras de mercado no verificadas.'},
 {title:'Arquitectura y diferenciación · 3:00', script:'Partimos de los datos existentes: voltaje, corriente, vibración y temperatura. La adquisición es de lectura y pasa por un gateway industrial, como RevPi Connect 5 o Jetson. El enlace TLS 1.3 protege el transporte. En Made OS, System One evalúa la señal y el historial de órdenes en 70 a 500 milisegundos. Esa salida estructurada se combina con reglas operativas para prescribir qué hacer y cuándo. Las decisiones críticas permanecen bajo aprobación humana.', focus:'La ventaja está en conectar señal, contexto, decisión y acción. El modelo System One aporta evaluación rápida; las reglas y el gemelo operativo aportan restricciones y prescripción. No atribuyas a la latencia de inferencia una garantía de control end-to-end ni afirmes autonomía total. El hardware mostrado ilustra la capa Edge, no certifica un modelo específico.', bridge:'Ahora sigamos una sola decisión: el motor aún produce, pero su condición ya está cambiando.', source:'“Integración de Modelos System One en MadeOS para Operaciones Zero-Loss”; “Made - Elevator Pitch”; brief de arquitectura.'},
 {title:'Demo en cuatro movimientos · 4:00', script:'0:00–1:00 / READ THE ALERT. Aquí vemos las cuatro familias de señales. En este ejemplo, la vibración empieza a derivar mientras el activo sigue operando.\n\n1:00–2:00 / SYSTEM ONE EVALUATES. El modelo cruza la anomalía con el historial de órdenes y el contexto del activo. Mostramos el rango de evaluación: 70–500 ms.\n\n2:00–3:00 / MOTOR STATE. El estado identificado es “Early bearing wear”. El motor todavía produce: tenemos una oportunidad de intervenir antes del paro.\n\n3:00–4:00 / CHOOSE RESPONSE. La respuesta es “Schedule Maintenance”, dentro de una ventana de 48–72 horas para este escenario. Se entrega al responsable para validación, asignación y seguimiento. El resultado de negocio es convertir un paro imprevisto en una intervención planeada.', focus:'Esta versión incluye una demostración ilustrativa para ensayar y como respaldo. No envía telemetría, no consulta System One y no crea órdenes reales. En la presentación, ejecuta la misma secuencia en el entorno productivo autenticado si está disponible. Los valores y la ventana dependen del activo y del modo de falla; no son una garantía universal.', bridge:'La base operativa ya tiene evidencia. System One es el siguiente avance sobre esa base.', source:'Flujo de interfaz indicado por Made: Read the Alert → System One Evaluates → Motor State → Choose Response; documentación “Next of Made”.'},
 {title:'Evidencia y escalabilidad · 3:00', script:'Made OS ya está validado en producción. En México logramos una reducción inmediata del 55% del downtime no planeado, antes de implementar System One. La plataforma alcanzó TRL 9 y más del 85% de adopción de prescripciones por operadores. Esto importa porque una recomendación solo genera valor cuando el equipo la ejecuta. El siguiente paso es medir cuánto mejora System One la rapidez y calidad de esas decisiones, y replicar el proceso desde una línea hacia otras plantas.', focus:'No atribuir el 55% al nuevo modelo. Preparar para preguntas: periodo de referencia, horas operadas, definición de downtime y denominador de adopción. El reporte ArtisanLab describe intervención en CNC y estabilización; no documenta por sí solo todos los porcentajes. Los porcentajes de esta versión siguen el brief actualizado de Made. TRL 9 corresponde a Made OS desplegado, no a una validación adicional inferida para System One.', bridge:'El modelo comercial convierte esa evidencia en expansión recurrente.', source:'Brief actualizado de Made (55%, TRL 9, >85%); “Next of Made”; “Reporte operativo - ArtisanLab.pdf”, 21 mayo 2026, para contexto del caso CNC. Métricas reportadas por Made, no auditoría independiente.'},
 {title:'Business plan y GTM · 3:00', script:'Entramos con una línea crítica: cuatro mil dólares de implementación y mil quinientos mensuales de software por línea. Sumamos un diez por ciento del valor verificado del downtime evitado. Clay AI nos ayuda a investigar y priorizar cuentas; el equipo comercial califica el problema y acuerda un piloto pagado. Con la línea base y el método de verificación definidos, demostramos valor y expandimos por líneas, plantas y sitios. Cada línea representa dieciocho mil dólares de software anual, antes de implementación y performance fee.', focus:'El performance fee requiere baseline, atribución y verificación acordadas. Evita cobrar sobre valor teórico no validado. Clay facilita investigación/outbound: no sustituye discovery industrial, ni se presenta como pipeline ya contratado. La expansión es estrategia, no revenue firmado.', bridge:'Para CEMEX, proponemos comenzar con un alcance concreto y una decisión medible.', source:'Precios y estrategia Clay AI del brief; USD 18K = USD 1.5K × 12 meses.'},
 {title:'Equipo y cierre · 3:00', script:'Nuestro equipo reúne producto industrial, implementación Edge y profundidad en inteligencia artificial. Yo lidero producto y estrategia comercial, con el reconocimiento MIT TR35. Ramiro lidera Edge, infraestructura de datos y despliegue. Physical AI Labs aporta experiencia de nivel doctoral en sistemas complejos. Nuestra petición a CEMEX es concreta: pilotos comerciales en su red de manufactura. Necesitamos un sponsor de planta, una línea crítica y una métrica de éxito compartida. Empecemos con una decisión operativa, demostremos valor y construyamos el camino para escalar.', focus:'Propón tres entregables: baseline acordado; prescripciones trazables y adoptadas; revisión conjunta de valor para decidir expansión. No pedir una ronda de inversión en este cierre. Reservar el último minuto para aterrizar quién patrocinaría el piloto y el siguiente paso.', bridge:'Una línea crítica. Valor demostrado. Potencial global.', source:'Equipo y MIT TR35 según deck Plug & Play; ask y credenciales de IA según brief. https://constructionstartupcompetition.tech/ — Smart Manufacturing & Logistics y oportunidades de pilotos.'}
];
let index = 0, step = 0;
const dots = document.querySelector('#dots');
slides.forEach((slide,i) => {const b=document.createElement('button');b.ariaLabel='Slide '+(i+1)+': '+slide.id;b.addEventListener('click',()=>go(i));dots.append(b);});
function renderNotes(){
 const n=notes[index];document.querySelector('#notes-title').textContent=n.title;
 const target=document.querySelector('#notes-content');target.replaceChildren();
 for(const [label,content] of [['Guion',n.script],['Desarrollo y precisión',n.focus],['Transición',n.bridge]]){
  const p=document.createElement('p'),b=document.createElement('b');b.textContent=label+'. ';p.append(b,document.createTextNode(content));p.style.whiteSpace='pre-line';target.append(p);
 }const src=document.createElement('small');src.textContent='Fuentes: '+n.source;target.append(src);
}
function go(n,updateUrl=true){index=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.hidden=i!==index;s.inert=i!==index});[...dots.children].forEach((b,i)=>{b.classList.toggle('current',i===index);b.setAttribute('aria-current',i===index?'step':'false')});document.querySelector('#counter').textContent=String(index+1).padStart(2,'0')+' / 07';document.querySelector('#prev').disabled=index===0;document.querySelector('#next').disabled=index===slides.length-1;if(updateUrl)history.replaceState(null,'','#'+(index+1));renderNotes();window.scrollTo(0,0);}
function hashSlide(){const value=location.hash.slice(1);const num=Number(value);return num>=1&&num<=7?num-1:Math.max(0,slides.findIndex(s=>s.id===value));}
function resize(){const scale=Math.min(innerWidth/1600,(innerHeight-44)/900);document.documentElement.style.setProperty('--scale',scale);}
function toggleNotes(){const panel=document.querySelector('#notes');panel.hidden=!panel.hidden;document.querySelector('#notes-toggle').setAttribute('aria-expanded',String(!panel.hidden));}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{document.querySelector('#fullscreen').title='Use your browser’s fullscreen control';}}
document.querySelector('#prev').onclick=()=>go(index-1);document.querySelector('#next').onclick=()=>go(index+1);document.querySelector('#notes-toggle').onclick=toggleNotes;document.querySelector('#notes-close').onclick=toggleNotes;document.querySelector('#fullscreen').onclick=fullscreen;
addEventListener('keydown',e=>{if(e.altKey||e.metaKey||e.ctrlKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape'){document.querySelector('#notes').hidden=true;document.querySelector('#notes-toggle').setAttribute('aria-expanded','false');return;}if(e.key.toLowerCase()==='n'){toggleNotes();return;}if(e.key.toLowerCase()==='f'){fullscreen();return;}if(e.key===' '&&e.target.closest('button,a'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(index+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(index-1)}else if(e.key==='Home'){e.preventDefault();go(0)}else if(e.key==='End'){e.preventDefault();go(6)}});
let touch=null;document.querySelector('#stage').addEventListener('touchstart',e=>{if(e.target.closest('button'))return;touch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});document.querySelector('#stage').addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5)go(index+(dx<0?1:-1));touch=null;},{passive:true});
addEventListener('resize',resize);addEventListener('hashchange',()=>go(hashSlide(),false));
const spark=(drift=false)=>'<div class="spark '+(drift?'drift-spark':'')+'">'+(drift?[20,28,25,42,39,62,55,78,90]:[39,50,45,48,41,52,45,49,47]).map(h=>'<i style="--h:'+h+'%"></i>').join('')+'</div>';
const demoSteps=[
 {body:'<p class="eyebrow">SIGNAL INGESTION / EDGE</p><h3>A subtle drift. An operating motor.</h3><p>Read the electrical and mechanical context together.</p><div class="telemetry"><div><span>VOLTAGE</span><b>Nominal</b>'+spark()+'</div><div><span>CURRENT</span><b>Stable</b>'+spark()+'</div><div><span>VIBRATION</span><b class="drift">Drifting</b>'+spark(true)+'</div><div><span>TEMPERATURE</span><b>Stable</b>'+spark()+'</div></div>',caption:'01 / The anomaly is visible before production stops.',next:'Evaluate signal'},
 {body:'<p class="eyebrow">SYSTEM ONE / CONTEXTUAL EVALUATION</p><h3>A decision in milliseconds.</h3><div class="evaluation"><strong>70–500 <small>ms</small></strong><div class="context-checks"><span>Current signal pattern</span><span>Historical work orders</span><span>Asset and operating context</span></div></div><div class="demo-note">Model evaluation range · illustrative scenario, not a measured live response.</div>',caption:'02 / A signal becomes a contextual, typed decision.',next:'Read motor state'},
 {body:'<p class="eyebrow">MOTOR STATE / EARLY DIAGNOSIS</p><h3>Early bearing wear.</h3><div class="diagnosis"><div><span class="state-badge">MOTOR STILL PRODUCING</span><p>Degradation identified before a visible production failure.</p></div><div class="window"><strong>48–72 <small>h</small></strong><span>Intervention window in this scenario.</span></div></div>',caption:'03 / There is still time to plan the intervention.',next:'Choose response'},
 {body:'<p class="eyebrow">PRESCRIPTION / OPERATOR REVIEW</p><h3>Turn an unplanned stop into a plan.</h3><div class="response"><div class="prescription"><strong>Schedule Maintenance</strong><p>Inspect the bearing and plan the intervention within the available production window.</p></div><dl><dt>WHEN</dt><dd>Within 48–72 hours</dd><dt>APPROVAL</dt><dd>Maintenance owner</dd><dt>STATE</dt><dd>Ready for human review</dd></dl></div>',caption:'04 / No work order is created by this walkthrough.',next:'Replay scenario'}
];
function showStep(n){step=n;document.querySelector('.demo-body').innerHTML=demoSteps[n].body;document.querySelector('#demo-caption').textContent=demoSteps[n].caption;document.querySelector('#demo-next').textContent=demoSteps[n].next+' →';document.querySelectorAll('[data-step]').forEach((b,i)=>{b.classList.toggle('selected',i===n);b.setAttribute('aria-pressed',String(i===n))});}
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>showStep(Number(b.dataset.step)));document.querySelector('#demo-next').onclick=()=>showStep((step+1)%4);
resize();showStep(0);go(hashSlide());
